'use client'

import { useEffect, useState } from 'react'
import { ArrowRight, Check, Gauge, Loader2, Lock, Search, ShieldCheck, Sparkles } from 'lucide-react'
import { getCountries, getCountryCallingCode, parsePhoneNumberFromString, type CountryCode } from 'libphonenumber-js'
import { Report, pink } from '@/components/audit-report'
import { trackAuditEvent } from '@/lib/analytics'

type Place={placeId:string;displayName:string;formattedAddress:string;types:string[]}
type Socials={instagram?:string;facebook?:string;tiktok?:string;[key:string]:string|undefined}
type Asset={kind:'website'|'social';platform?:string;url:string;source:string;verification:string}
type Detail={placeId:string;name:string;address:string;websiteUrl:string;googleWebsiteUrl?:string;rating:number|null;reviewCount:number|null;primaryType:string;socials:Socials;brandAssets?:Asset[];[key:string]:unknown}
type Lead={name:string;email:string;phone:string;role:string}
const stages=['Reading your website and ordering path','Measuring reviews, social activity and trust','Building your local market context','Scoring your growth engine','Preparing your growth audit']
const roles=['Owner','Manager','Marketing','Operations','Other']
const preferred:CountryCode[]=['US','CA','GB','AU','AE','PK','IN']

function Header(){return <header className="brand-header mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-6"><a href="https://tossdown.com" target="_blank" rel="noopener noreferrer" className="text-xl font-semibold tracking-[-.04em]">tossdown<span style={{color:pink}}>.</span></a><a href="https://tossdown.com" target="_blank" rel="noopener noreferrer" className="rounded-full bg-foreground px-4 py-2 text-xs font-semibold text-background">Visit tossdown <ArrowRight className="ml-1 inline h-3.5 w-3.5"/></a></header>}
function Steps({active}:{active:0|1|2|3}){return <div className="mx-auto mb-6 grid max-w-2xl grid-cols-4 rounded-2xl border border-border bg-card p-2 shadow-sm">{['Find','Confirm','Audit','Unlock'].map((s,i)=><div key={s} className={`flex items-center justify-center gap-2 rounded-xl px-2 py-2 text-xs font-semibold ${i===active?'bg-foreground text-background':'text-muted-foreground'}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full ${i<active?'bg-primary text-white':'bg-muted'}`}>{i<active?<Check className="h-3.5 w-3.5"/>:i+1}</span><span className="hidden sm:inline">{s}</span></div>)}</div>}
function Sample(){return <section className="mx-auto max-w-6xl px-5 pb-24 sm:px-6"><div className="grid gap-5 md:grid-cols-[.8fr_1.2fr]"><div className="rounded-[2rem] bg-primary p-8 text-white"><Sparkles/><p className="mt-8 text-xs font-semibold uppercase tracking-[.2em] text-white/70">What you get</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.05em]">A practical growth score, not another checklist.</h2><p className="mt-4 leading-7 text-white/75">We connect discovery, direct ordering, reputation and repeat-customer paths.</p></div><div className="rounded-[2rem] border border-border bg-card p-8 shadow-sm"><div className="flex justify-between"><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">Sample result</p><span className="rounded-full bg-muted px-3 py-1 text-xs">Illustrative</span></div><div className="mt-7 grid grid-cols-3 gap-3">{[['74','Growth score'],['3','Priority leaks'],['5','Channels checked']].map(([v,l])=><div key={l} className="rounded-2xl bg-muted p-4"><b className="text-3xl">{v}</b><p className="mt-1 text-xs text-muted-foreground">{l}</p></div>)}</div><p className="mt-6 text-sm text-muted-foreground">Your result is generated from the restaurant and website you confirm.</p></div></div></section>}

export default function Home(){
 const [query,setQuery]=useState(''),[suggestions,setSuggestions]=useState<Place[]>([]),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(false),[audit,setAudit]=useState<any>(null),[error,setError]=useState(''),[auditStage,setAuditStage]=useState(0),[showLead,setShowLead]=useState(false),[unlocked,setUnlocked]=useState(false)
 useEffect(()=>{const t=setTimeout(async()=>{if(query.trim().length<3){setSuggestions([]);return}try{const r=await fetch(`/api/places/autocomplete?input=${encodeURIComponent(query)}`),d=await r.json();setSuggestions(d.suggestions??[]);if(d.error)setError(d.error)}catch{setError('Search is temporarily unavailable. Enter the restaurant manually below.')}},350);return()=>clearTimeout(t)},[query])
 async function choose(p:Place){setLoading(true);setSuggestions([]);try{const r=await fetch(`/api/places/details?placeId=${p.placeId}`),d=await r.json();if(!r.ok){setError(d.error??'Could not load location.');return}setDetail(d);trackAuditEvent('restaurant_selected',{restaurant_category:d.primaryType||'unknown',has_google_website:Boolean(d.googleWebsiteUrl||d.websiteUrl)});try{const q=new URLSearchParams({name:d.name,address:d.address});if(d.websiteUrl)q.set('url',d.websiteUrl);const sr=await fetch(`/api/social/discover?${q}`),sd=await sr.json();const assets:Asset[]=Array.isArray(sd.assets)?sd.assets:[];const social=Object.fromEntries(assets.filter(a=>a.kind==='social'&&a.platform&&a.verification!=='candidate_needs_confirmation').map(a=>[a.platform!,a.url]));const found=sd.websiteUrl||assets.find(a=>a.kind==='website')?.url||'';console.info('[growth-audit][asset-discovery]',{restaurant:d.name,status:sr.status,websiteUrl:found,platforms:Object.keys(sd.socials??{}),diagnostics:sd.diagnostics});setDetail(prev=>prev?{...prev,websiteUrl:prev.googleWebsiteUrl||prev.websiteUrl||found,socials:{...social,...d.socials},brandAssets:assets,discoveryDiagnostics:sd.diagnostics}:prev)}catch(e){console.warn('[growth-audit][asset-discovery] request failed',e)}}finally{setLoading(false)}}
 function manual(){if(query.trim().length<2){setError('Enter your restaurant name first.');return}setDetail({placeId:`manual_${Date.now()}`,name:query.trim(),address:'Location entered manually',websiteUrl:'',rating:null,reviewCount:null,primaryType:'Restaurant',socials:{}});setSuggestions([]);setError('')}
 async function runAudit(){if(!detail)return;const current=detail;trackAuditEvent('audit_started',{restaurant_category:current.primaryType||'unknown',has_website:Boolean(current.websiteUrl),social_profile_count:Object.keys(current.socials).length});setLoading(true);setAuditStage(0);setError('');const timer=window.setInterval(()=>setAuditStage(s=>Math.min(s+1,stages.length-1)),1800);try{const r=await fetch('/api/direct-audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(current)}),d=await r.json();if(!r.ok){setError(d.error??'Audit failed.');return}setAudit(d);setShowLead(true);trackAuditEvent('audit_completed',{growth_score:typeof d.result?.score==='number'?d.result.score:0,evidence_coverage:typeof d.result?.coverage==='number'?d.result.coverage:0})}catch{setError('Audit could not connect.')}finally{clearInterval(timer);setLoading(false)}}
 async function unlock(lead:Lead){if(!detail||!audit)return;const id=`sub_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;trackAuditEvent('generate_lead',{restaurant_category:detail.primaryType||'unknown'});fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,submissionId:id,profile:{placeId:detail.placeId,name:detail.name}})}).catch(()=>{});setUnlocked(true);setShowLead(false);persist(detail,audit,lead,id)}
 async function persist(current:Detail,data:any,lead:Lead,id:string){try{const r=await fetch('/api/audits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({detail:current,audit:data,lead})});if(!r.ok)return;const saved=await r.json();if(!saved.url)return;trackAuditEvent('report_shared',{growth_score:data.result?.score??0});if(saved.id)history.replaceState(null,'',`/r/${saved.id}`);fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,submissionId:id,reportUrl:saved.url,reportSummary:{score:data.result?.score,rating:current.rating,reviews:current.reviewCount}})}).catch(()=>{})}catch{}}
 if(audit&&unlocked)return <Report audit={audit} onReset={()=>{setAudit(null);setDetail(null);setQuery('');setShowLead(false);setUnlocked(false);history.replaceState(null,'','/')}}/>
 if(audit&&showLead&&detail)return <LockedReport audit={audit} restaurant={detail.name} back={()=>{setAudit(null);setShowLead(false)}} submit={unlock}/>
 if(loading&&detail)return <Running name={detail.name} stage={auditStage}/>
 return <main className="min-h-screen"><Header/><section className="mx-auto max-w-6xl px-5 pb-14 pt-10 sm:px-6 md:pt-16"><Steps active={detail?1:0}/><div className="hero-panel p-7 md:p-12"><div className="max-w-3xl"><p className="mb-6 text-xs font-semibold uppercase tracking-[.22em] text-pink-200">Free restaurant growth audit</p><h1 className="text-balance text-5xl font-semibold leading-[1.03] tracking-[-.065em] md:text-7xl">Every empty seat has a reason. Let&apos;s find yours.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">Find where customers discover you, where orders leak, and whether they have a reason to return.</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-semibold text-white/75">{['Free','About 2 minutes','No login'].map(x=><span key={x} className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5">{x}</span>)}</div><div className="relative mt-9 max-w-xl"><div className="flex items-center gap-3 rounded-2xl bg-white px-5 py-4 text-foreground shadow-2xl"><Search className="h-5 w-5 text-muted-foreground"/><input value={query} onChange={e=>{setQuery(e.target.value);setError('')}} placeholder="Search for your restaurant…" className="w-full bg-transparent outline-none"/>{loading&&<Loader2 className="h-5 w-5 animate-spin"/>}</div>{suggestions.length>0&&<div className="absolute z-10 mt-2 max-h-72 w-full overflow-y-auto rounded-2xl border border-border bg-card p-2 text-foreground shadow-xl">{suggestions.map(p=><button key={p.placeId} onClick={()=>choose(p)} className="w-full rounded-xl px-4 py-3 text-left hover:bg-muted"><b className="block">{p.displayName}</b><span className="text-sm text-muted-foreground">{p.formattedAddress}</span></button>)}</div>}</div><button onClick={manual} className="mt-4 text-sm text-white/70 hover:text-white hover:underline">Can&apos;t find it? Enter details manually</button>{error&&<p className="mt-3 text-sm text-pink-200">{error}</p>}</div><div className="mt-14 grid gap-3 border-t border-white/15 pt-7 text-sm text-white/65 md:grid-cols-3"><p><b className="mb-2 block text-white">01 · Attract</b>Are customers choosing you?</p><p><b className="mb-2 block text-white">02 · Convert</b>Can they order directly?</p><p><b className="mb-2 block text-white">03 · Retain</b>Can you bring them back?</p></div></div></section><Sample/>{detail&&<Confirm detail={detail} setDetail={setDetail} next={runAudit}/>}</main>
}

function Confirm({detail,setDetail,next}:{detail:Detail;setDetail:(d:Detail|null)=>void;next:()=>void}){const [err,setErr]=useState('');function proceed(){try{const u=new URL(detail.websiteUrl.trim());if(!/^https?:$/.test(u.protocol))throw new Error()}catch{setErr('Website could not be found. Add a valid website URL to continue.');return}next()}const missing=!detail.googleWebsiteUrl;return <Overlay step={1}><button onClick={()=>setDetail(null)} className="mb-6 text-sm text-muted-foreground">← Search again</button><div className="rounded-[2rem] border border-border bg-card p-7 shadow-xl md:p-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Confirm the right restaurant</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">{detail.name}</h2><p className="mt-2 text-muted-foreground">{detail.address}</p><div className="mt-7 rounded-2xl bg-muted p-4 text-sm leading-6"><b>Why this matters:</b> your website anchors the ordering and customer-relationship checks. Social profiles are optional.</div><div className="mt-7 grid gap-4"><Field label="Website · required" value={detail.websiteUrl} onChange={v=>{setErr('');setDetail({...detail,websiteUrl:v})}} placeholder="https://yourrestaurant.com" hint={missing?'Not linked on the selected Google Business Profile. Please confirm or add it.':''} error={err}/>{['instagram','facebook','tiktok'].map(k=><Field key={k} label={k[0].toUpperCase()+k.slice(1)} value={detail.socials[k]||''} onChange={v=>setDetail({...detail,socials:{...detail.socials,[k]:v}})} placeholder={`https://${k}.com/…`}/>)}</div><button onClick={proceed} className="mt-8 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-4 font-semibold text-white">Preview what we&apos;ll audit <ArrowRight className="h-5 w-5"/></button></div></Overlay>}
function Overlay({step,children}:{step:0|1|2|3;children:React.ReactNode}){return <div className="fixed inset-0 z-20 overflow-y-auto bg-background/75 px-5 py-8 backdrop-blur-sm"><Steps active={step}/><div className="mx-auto max-w-2xl">{children}</div></div>}
function Running({name,stage}:{name:string;stage:number}){return <main className="min-h-screen"><Header/><section className="mx-auto max-w-3xl px-5 py-12"><Steps active={2}/><div className="audit-running-card rounded-[2rem] border border-border bg-card p-8 shadow-2xl"><div className="audit-orbit"><Gauge className="h-10 w-10 text-primary"/></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.2em] text-primary">Auditing {name}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.06em]">Reading your restaurant growth engine.</h1><p className="mt-3 text-muted-foreground">Live public signals are being gathered and connected into one report.</p><div className="mt-8 grid gap-3">{stages.map((x,i)=><div key={x} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm transition-all ${i===stage?'bg-muted text-foreground shadow-sm':'text-muted-foreground'}`}><span className="flex h-7 w-7 items-center justify-center rounded-full border border-border">{i<stage?<Check className="h-4 w-4"/>:i===stage?<Loader2 className="h-4 w-4 animate-spin text-primary"/>:i+1}</span>{x}</div>)}</div></div></section></main>}
function Field({label,value,onChange,placeholder,hint,error}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;hint?:string;error?:string}){return <label className="grid gap-2 text-sm font-medium">{label}<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={`rounded-xl border bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-primary/30 ${error?'border-danger':'border-border'}`}/>{hint&&<span className="text-xs font-normal text-muted-foreground">{hint}</span>}{error&&<span className="text-xs font-normal text-danger">{error}</span>}</label>}
function countries(){const all=getCountries();return [...preferred.filter(c=>all.includes(c)),...all.filter(c=>!preferred.includes(c)).sort()]}
function LockedReport({audit,restaurant,back,submit}:{audit:any;restaurant:string;back:()=>void;submit:(x:Lead)=>void}){return <main className="relative h-screen overflow-hidden bg-background"><div className="pointer-events-none select-none opacity-55 blur-[7px]" aria-hidden="true"><Report audit={audit} onReset={()=>{}}/></div><div className="absolute inset-0 bg-gradient-to-b from-background/20 via-background/35 to-background/70"/><LeadForm restaurant={restaurant} back={back} submit={submit}/></main>}
function LeadForm({restaurant,back,submit}:{restaurant:string;back:()=>void;submit:(x:Lead)=>void}){const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[role,setRole]=useState('Owner'),[country,setCountry]=useState<CountryCode>('US'),[err,setErr]=useState('');function send(e:React.FormEvent){e.preventDefault();const national=country==='PK'?phone.trim().replace(/^0/,''):phone.trim();const parsed=parsePhoneNumberFromString(national,country);if(!name.trim())return setErr('Please enter your name.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return setErr('Please enter a valid email.');if(!parsed?.isValid())return setErr('Please enter a valid phone number.');submit({name,email,phone:parsed.number,role})}return <Overlay step={3}><div className="mx-auto max-w-xl"><form onSubmit={send} className="rounded-[2rem] border border-border bg-card p-7 shadow-2xl md:p-9"><button type="button" onClick={back} className="mb-5 text-sm text-muted-foreground">← Start again</button><p className="flex gap-2 text-xs font-semibold uppercase tracking-[.18em] text-primary"><Lock className="h-4 w-4"/>Your audit is complete</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em]">Unlock {restaurant}&apos;s report.</h2><p className="mt-2 text-sm text-muted-foreground">Your results are ready. Add your details to reveal the complete score, evidence and priorities.</p><div className="mt-6 grid gap-4"><Field label="Full name" value={name} onChange={setName} placeholder="Jane Doe"/><Field label="Work email" value={email} onChange={setEmail} placeholder="jane@restaurant.com"/><label className="grid gap-2 text-sm font-medium">Phone<div className="flex gap-2"><select value={country} onChange={e=>{setCountry(e.target.value as CountryCode);setErr('')}} className="rounded-xl border border-border bg-background px-2">{countries().map(c=><option key={c} value={c}>{c} +{getCountryCallingCode(c)}</option>)}</select><input value={phone} onChange={e=>{setPhone(e.target.value);setErr('')}} inputMode="tel" autoComplete="tel-national" placeholder={country==='PK'?'321 4007711':'Phone number'} className="w-full rounded-xl border border-border bg-background px-3 py-3"/></div></label><label className="grid gap-2 text-sm font-medium">Role<select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3">{roles.map(r=><option key={r}>{r}</option>)}</select></label></div>{err&&<p className="mt-3 text-sm text-danger">{err}</p>}<button className="mt-6 w-full rounded-xl bg-primary px-5 py-4 font-semibold text-white">Unlock my complete report</button><p className="mt-4 flex justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4"/>Private, no login required.</p></form></div></Overlay>}
