'use client'
import { useEffect, useState } from 'react'
import { ArrowRight, Check, Loader2, Search, ShieldCheck, Activity, Gauge, Lock } from 'lucide-react'
import { Report, pink, PLATFORM_LABEL } from '@/components/audit-report'
import { getCountries, getCountryCallingCode, parsePhoneNumberFromString, type CountryCode } from 'libphonenumber-js'

type Place={placeId:string;name:string;displayName:string;formattedAddress:string;types:string[]}; type Socials={instagram?:string;facebook?:string;tiktok?:string;youtube?:string;twitter?:string;threads?:string;linkedin?:string;pinterest?:string;snapchat?:string;whatsapp?:string}; type BrandAsset={kind:'website'|'social';platform?:string;url:string;source:'gmb'|'website'|'search';verification:'linked_on_gmb'|'verified_brand_asset_missing_from_gmb'|'verified_brand_asset'|'candidate_needs_confirmation';confidence:'limited'|'medium'|'high';evidence:string[]}; type Detail={placeId:string;name:string;address:string;websiteUrl:string;googleWebsiteUrl?:string;rating:number|null;reviewCount:number|null;primaryType:string;types?:string[];priceLevel?:string|null;lat?:number;lng?:number;openingHours?:{daysOpen:number|null;weekdayDescriptions:string[]}|null;socials:Socials;brandAssets?:BrandAsset[]}
const OTHER_PLATFORMS:Array<keyof Socials>=['youtube','twitter','threads','linkedin','pinterest','snapchat','whatsapp']
const auditStages=['Reading your website and ordering path','Measuring reviews, social activity and trust','Building a local competitive benchmark','Scoring your growth engine','Preparing your restaurant growth audit']
export default function Home(){const [query,setQuery]=useState(''); const [suggestions,setSuggestions]=useState<Place[]>([]); const [detail,setDetail]=useState<Detail|null>(null); const [loading,setLoading]=useState(false); const [audit,setAudit]=useState<any>(null); const [error,setError]=useState(''); const [auditStage,setAuditStage]=useState(0); const [showLead,setShowLead]=useState(false); const [shareUrl,setShareUrl]=useState<string|null>(null)
 useEffect(()=>{const t=setTimeout(async()=>{if(query.trim().length<3){setSuggestions([]);return} const r=await fetch(`/api/places/autocomplete?input=${encodeURIComponent(query)}`); const d=await r.json(); setSuggestions(d.suggestions??[]); if(d.error)setError(d.error)},350);return()=>clearTimeout(t)},[query])
 async function choose(p:Place){setLoading(true);setSuggestions([]);setQuery(p.displayName);const r=await fetch(`/api/places/details?placeId=${p.placeId}`);const d=await r.json();if(r.ok){setDetail(d);try{const qs=new URLSearchParams();if(d.websiteUrl)qs.set('url',d.websiteUrl);if(d.name)qs.set('name',d.name);if(d.address)qs.set('address',d.address);const sr=await fetch(`/api/social/discover?${qs.toString()}`);const sd=await sr.json();const assets:Array<BrandAsset>=Array.isArray(sd?.assets)?sd.assets:[];const verifiedWebsite=assets.find(asset=>asset.kind==='website'&&asset.verification==='verified_brand_asset_missing_from_gmb');const verifiedSocials=Object.fromEntries(assets.filter(asset=>asset.kind==='social'&&asset.platform&&asset.verification!=='candidate_needs_confirmation').map(asset=>[asset.platform as string,asset.url]));if(Object.keys(verifiedSocials).length||verifiedWebsite){setDetail((prev:Detail|null)=>prev?{...prev,websiteUrl:verifiedWebsite?.url||prev.websiteUrl,socials:{...verifiedSocials,...prev.socials},brandAssets:assets}:prev)}}catch{/* discovery is best-effort */}}else setError(d.error??'Could not load location.');setLoading(false)}
 // Client lifecycle (ported from the previous project): generate one submissionId,
 // fire a best-effort lead capture, run the EXISTING audit, then persist + share +
 // second lead merge. Persistence never blocks or breaks the audit experience.
 async function unlock(lead:{name:string;email:string;phone:string;role:string}){if(!detail)return;const submissionId=`sub_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;const currentDetail=detail;
  // 1) best-effort first lead — do NOT await
  fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,submissionId,profile:{placeId:currentDetail.placeId,name:currentDetail.name}})}).catch(()=>{});
  setShowLead(false);setLoading(true);setAuditStage(0);setError('');const timer=window.setInterval(()=>setAuditStage(s=>Math.min(s+1,auditStages.length-1)),1800);
  try{const r=await fetch('/api/direct-audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(currentDetail)});const d=await r.json();if(!r.ok){setError(d.error??'Audit failed.');return}setAudit(d);persist(currentDetail,d,lead,submissionId)}catch{setError('Audit could not connect. Check the debug logs for provider details.')}finally{window.clearInterval(timer);setLoading(false)}}
 // Best-effort persistence: save the completed audit, mint /r/{id}, and fire a
 // SECOND /api/lead with the same submissionId to merge report data into the lead.
 async function persist(currentDetail:Detail,auditData:any,lead:{name:string;email:string;phone:string;role:string},submissionId:string){try{const r=await fetch('/api/audits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({detail:currentDetail,audit:auditData,lead})});if(!r.ok)return;const {id,url}=await r.json();if(!url)return;setShareUrl(url);try{if(id)window.history.replaceState(null,'',`/r/${id}`)}catch{}const topGaps=(auditData.interpretation?.priorities||[]).slice(0,3).map((p:any)=>typeof p==='string'?p:(p?.title||p?.action||p?.whyItMatters||'')).filter(Boolean).join(' · ');fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,submissionId,reportUrl:url,reportSummary:{score:auditData.result?.score,rating:currentDetail.rating??auditData.reviews?.googleRating??null,reviews:currentDetail.reviewCount??auditData.reviews?.googleReviewCount??null,topGaps}})}).catch(()=>{})}catch{/* persistence is best-effort */}}
 if(audit)return <Report audit={audit} onReset={()=>{setAudit(null);setDetail(null);setQuery('');setShowLead(false);setShareUrl(null);try{window.history.replaceState(null,'','/')}catch{}}} />
 if(loading&&detail)return <AuditRunning name={detail.name} stage={auditStage} />
 return <main className="min-h-screen"><header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><div className="text-xl font-semibold tracking-[-0.04em]">tossdown<span style={{color:pink}}>.</span></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4"/> Private, no login required</div></header><section className="mx-auto max-w-6xl px-6 pb-24 pt-16 md:pt-28"><div className="max-w-3xl"><p className="mb-6 text-xs font-semibold uppercase tracking-[0.22em]" style={{color:pink}}>Restaurant growth audit · V1</p><h1 className="text-balance text-5xl font-semibold leading-[1.03] tracking-[-0.065em] md:text-7xl">How strong is your restaurant growth engine?</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">See where growth is working — and where customers, orders or repeat visits are leaking.</p><div className="relative mt-10 max-w-xl"><div className="flex items-center gap-3 rounded-2xl border border-border bg-card px-5 py-4 shadow-sm"><Search className="h-5 w-5 text-muted-foreground"/><input value={query} onChange={e=>{setQuery(e.target.value);setError('')}} placeholder="Search for your restaurant…" className="w-full bg-transparent outline-none placeholder:text-muted-foreground" aria-label="Search for your restaurant"/>{loading&&<Loader2 className="h-5 w-5 animate-spin text-muted-foreground"/>}</div>{suggestions.length>0&&<div className="absolute z-10 mt-2 w-full overflow-hidden rounded-2xl border border-border bg-card p-2 shadow-xl">{suggestions.map(p=><button key={p.placeId} onClick={()=>choose(p)} className="flex w-full flex-col items-start rounded-xl px-4 py-3 text-left hover:bg-muted"><span className="font-medium">{p.displayName}</span><span className="text-sm text-muted-foreground">{p.formattedAddress}</span></button>)}</div>}</div>{error&&<p className="mt-3 text-sm text-danger">{error}</p>}</div><div className="mt-24 grid gap-4 border-t border-border pt-8 text-sm text-muted-foreground md:grid-cols-3"><div><span className="mb-2 block font-medium text-foreground">01 · Attract</span>Are customers choosing and trusting you?</div><div><span className="mb-2 block font-medium text-foreground">02 · Convert</span>Can they order from you directly?</div><div><span className="mb-2 block font-medium text-foreground">03 · Retain</span>Do you have a visible path to bring them back?</div></div></section>{detail&&!showLead&&<Confirm detail={detail} setDetail={setDetail} onContinue={()=>setShowLead(true)} loading={loading}/>}{detail&&showLead&&<LeadForm restaurant={detail.name} onBack={()=>setShowLead(false)} onSubmit={unlock}/>}</main>}
function Confirm({detail,setDetail,onContinue,loading}:{detail:Detail;setDetail:(d:Detail|null)=>void;onContinue:()=>void;loading:boolean}){return <div className="fixed inset-0 z-20 overflow-y-auto bg-background/95 px-6 py-10 backdrop-blur-sm"><div className="mx-auto max-w-2xl"><button onClick={()=>setDetail(null)} className="mb-8 text-sm text-muted-foreground hover:text-foreground">← Search again</button><div className="rounded-3xl border border-border bg-card p-7 shadow-sm md:p-10"><p className="text-xs font-semibold uppercase tracking-[0.18em]" style={{color:pink}}>Confirm location</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">{detail.name}</h2><p className="mt-2 text-muted-foreground">{detail.address}</p><div className="mt-6 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-muted px-3 py-1.5">{detail.primaryType||'Restaurant'}</span>{detail.rating&&<span className="rounded-full bg-muted px-3 py-1.5">★ {detail.rating} · {detail.reviewCount?.toLocaleString()} reviews</span>}</div><div className="mt-10 grid gap-4"><Field label="Website" value={detail.websiteUrl} onChange={v=>setDetail({...detail,websiteUrl:v})} placeholder="https://yourrestaurant.com"/><Field label="Instagram" value={detail.socials.instagram||''} onChange={v=>setDetail({...detail,socials:{...detail.socials,instagram:v}})} placeholder="https://instagram.com/…"/><Field label="Facebook" value={detail.socials.facebook||''} onChange={v=>setDetail({...detail,socials:{...detail.socials,facebook:v}})} placeholder="https://facebook.com/…"/><Field label="TikTok" value={detail.socials.tiktok||''} onChange={v=>setDetail({...detail,socials:{...detail.socials,tiktok:v}})} placeholder="https://tiktok.com/@…"/>{OTHER_PLATFORMS.some(k=>detail.socials[k])&&<div className="mt-2 grid gap-4 rounded-2xl border border-dashed border-border p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Other profiles found</p>{OTHER_PLATFORMS.filter(k=>detail.socials[k]).map(k=><Field key={k} label={PLATFORM_LABEL[k]} value={detail.socials[k]||''} onChange={v=>setDetail({...detail,socials:{...detail.socials,[k]:v}})} placeholder={`https://��`}/>)}</div>}</div><button onClick={onContinue} disabled={loading} className="mt-8 flex w-full items-center justify-center gap-2 rounded-xl px-5 py-4 font-semibold text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-60" style={{background:pink}}><span>Continue</span><ArrowRight className="h-5 w-5"/></button></div></div></div>}
function AuditRunning({name,stage}:{name:string;stage:number}){return <main className="min-h-screen"><header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><div className="text-xl font-semibold tracking-[-0.04em]">tossdown<span style={{color:pink}}>.</span></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Activity className="h-4 w-4 animate-pulse" style={{color:pink}}/> Live audit</div></header><section className="mx-auto flex min-h-[70vh] max-w-3xl flex-col justify-center px-6 py-16"><div className="relative overflow-hidden rounded-[2rem] border border-border bg-card p-8 shadow-2xl md:p-12"><div className="absolute inset-x-0 top-0 h-1 overflow-hidden bg-muted"><div className="h-full animate-[audit-progress_2s_ease-in-out_infinite]" style={{background:pink}} /></div><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-pink/10" style={{backgroundColor:'color-mix(in srgb, #ed1f5b 14%, transparent)'}}><Gauge className="h-8 w-8 animate-pulse" style={{color:pink}} /></div><p className="mt-8 text-xs font-semibold uppercase tracking-[0.2em]" style={{color:pink}}>Auditing {name}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.06em]">Reading the full restaurant growth engine.</h1><p className="mt-4 text-lg leading-8 text-muted-foreground">This takes a moment while we inspect ordering, reputation, social activity, repeat-customer paths, measurement signals and local competitive context.</p><div className="mt-10 grid gap-3">{auditStages.map((item,index)=><div key={item} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm transition-all ${index===stage?'bg-muted text-foreground':'text-muted-foreground'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full border ${index<stage?'border-transparent bg-foreground text-background':index===stage?'border-current':'border-border'}`}>{index<stage?<Check className="h-4 w-4"/>:index===stage?<Loader2 className="h-4 w-4 animate-spin"/>:<span>{index+1}</span>}</span>{item}</div>)}</div></div></section></main>}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="grid gap-2 text-sm font-medium">{label}<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="rounded-xl border border-border bg-background px-4 py-3 font-normal outline-none ring-primary/30 focus:ring-2"/></label>}

const ROLES=['Owner','Manager','Marketing','Operations','Other']
// Country list for the phone selector, sorted with common markets first.
const PREFERRED_COUNTRIES:CountryCode[]=['US','CA','GB','AU','AE','PK','IN']
function countryOptions(){const all=getCountries();const rest=all.filter(c=>!PREFERRED_COUNTRIES.includes(c)).sort();return [...PREFERRED_COUNTRIES.filter(c=>all.includes(c)),...rest]}
function LeadForm({restaurant,onBack,onSubmit}:{restaurant:string;onBack:()=>void;onSubmit:(lead:{name:string;email:string;phone:string;role:string})=>void}){
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [role,setRole]=useState('Owner')
  const [country,setCountry]=useState<CountryCode>('US');const [phone,setPhone]=useState('');const [err,setErr]=useState('')
  const countries=countryOptions()
  function submit(e:React.FormEvent){e.preventDefault();setErr('')
    if(!name.trim())return setErr('Please enter your name.')
    if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))return setErr('Please enter a valid email.')
    const parsed=parsePhoneNumberFromString(phone,country)
    if(!parsed||!parsed.isValid())return setErr('Please enter a valid phone number for the selected country.')
    onSubmit({name:name.trim(),email:email.trim(),phone:parsed.number,role})
  }
  return <div className="fixed inset-0 z-20 overflow-y-auto bg-background/95 px-6 py-10 backdrop-blur-sm"><div className="mx-auto max-w-xl"><button onClick={onBack} className="mb-8 text-sm text-muted-foreground hover:text-foreground">← Back</button><form onSubmit={submit} className="rounded-3xl border border-border bg-card p-7 shadow-sm md:p-10"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em]" style={{color:pink}}><Lock className="h-4 w-4"/>One last step</div><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">Where should we send the report?</h2><p className="mt-2 text-muted-foreground">We&apos;ll generate your audit for <span className="font-medium text-foreground">{restaurant}</span> and give you a shareable link.</p>
    <div className="mt-8 grid gap-4">
      <Field label="Full name" value={name} onChange={setName} placeholder="Jane Doe"/>
      <Field label="Work email" value={email} onChange={setEmail} placeholder="jane@restaurant.com"/>
      <label className="grid gap-2 text-sm font-medium">Phone<div className="flex gap-2"><select value={country} onChange={e=>setCountry(e.target.value as CountryCode)} className="rounded-xl border border-border bg-background px-3 py-3 font-normal outline-none ring-primary/30 focus:ring-2" aria-label="Country code">{countries.map(c=><option key={c} value={c}>{c} +{getCountryCallingCode(c)}</option>)}</select><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="Phone number" className="w-full rounded-xl border border-border bg-background px-4 py-3 font-normal outline-none ring-primary/30 focus:ring-2"/></div></label>
      <label className="grid gap-2 text-sm font-medium">Your role<select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl border border-border bg-background px-4 py-3 font-normal outline-none ring-primary/30 focus:ring-2">{ROLES.map(r=><option key={r} value={r}>{r}</option>)}</select></label>
    </div>
    {err&&<p className="mt-4 text-sm text-danger">{err}</p>}
    <button type="submit" className="mt-8 flex w-full items-center justify-center gap-2 rounded-xl px-5 py-4 font-semibold text-primary-foreground transition-opacity hover:opacity-90" style={{background:pink}}><span>Run my restaurant growth audit</span><ArrowRight className="h-5 w-5"/></button>
    <p className="mt-4 text-center text-xs text-muted-foreground">Private and secure. We use this only to send your report.</p>
  </form></div></div>
}
