'use client'

import { useEffect, useState } from 'react'
import Image from 'next/image'
import { Activity, ArrowRight, BarChart3, CalendarDays, Check, CheckCircle2, Eye, Gauge, Loader2, Search, ShieldCheck, Users } from 'lucide-react'
import { getCountries, getCountryCallingCode, parsePhoneNumberFromString, type CountryCode } from 'libphonenumber-js'
import { Report } from '@/components/audit-report'
import { trackAuditEvent } from '@/lib/analytics'

type Place={placeId:string;displayName:string;formattedAddress:string;types:string[]}
type Socials={instagram?:string;facebook?:string;tiktok?:string;[key:string]:string|undefined}
type Asset={kind:'website'|'social';platform?:string;url:string;source:string;verification:string}
type Detail={placeId:string;name:string;address:string;websiteUrl:string;googleWebsiteUrl?:string;rating:number|null;reviewCount:number|null;primaryType:string;socials:Socials;brandAssets?:Asset[];[key:string]:unknown}
type Lead={name:string;email:string;phone:string;role:string}
const stages=['Reading your website and ordering path','Measuring reviews, social activity and trust','Building your local market context','Scoring your growth engine','Preparing your growth audit']
const roles=['Owner','Manager','Marketing','Operations','Other']
const preferred:CountryCode[]=['US','CA','GB','AU','AE','PK','IN']

function Header({landing=false}:{landing?:boolean}){return <header className={`${landing?'':'brand-header'} mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-5 sm:px-6`}><a href="https://tossdown.com" target="_blank" rel="noopener noreferrer" aria-label="Visit tossdown"><Image src="/tossdown-logo.png" alt="tossdown" width={414} height={79} priority className="h-auto w-[118px] sm:w-[132px]"/></a>{landing?<span className="flex shrink-0 items-center gap-1.5 text-[11px] font-semibold text-[#7a6c5c] sm:text-xs"><CheckCircle2 className="h-4 w-4 text-[#1e9a56]"/>Free, takes 2 minutes</span>:<a href="https://tossdown.com" target="_blank" rel="noopener noreferrer" className="rounded-full bg-foreground px-4 py-2 text-xs font-semibold text-background">Visit tossdown <ArrowRight className="ml-1 inline h-3.5 w-3.5"/></a>}</header>}
function Steps({active}:{active:0|1|2}){return <div className="mx-auto mb-6 grid max-w-2xl grid-cols-3 rounded-2xl border border-border bg-card p-2 shadow-sm">{['Find','Verify & audit','View report'].map((s,i)=><div key={s} className={`flex items-center justify-center gap-2 rounded-xl px-2 py-2 text-xs font-semibold ${i===active?'bg-foreground text-background':'text-muted-foreground'}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full ${i<=active?'bg-primary text-white':'bg-muted text-muted-foreground'}`}>{i<active?<Check className="h-3.5 w-3.5"/>:i+1}</span><span className="hidden sm:inline">{s}</span></div>)}</div>}

function LandingSearch({query,setQuery,suggestions,loading,error,choose,submit,active,onActivate,darkButton=false,note}:{query:string;setQuery:(value:string)=>void;suggestions:Place[];loading:boolean;error:string;choose:(place:Place)=>void;submit:()=>void;active:boolean;onActivate:()=>void;darkButton?:boolean;note:string}){
 return <div>
  <div className="relative">
   <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-[#ebe0ce] bg-white p-2 pl-5 shadow-[0_18px_34px_-18px_rgba(36,27,22,.25)]">
    <Search className="h-5 w-5 shrink-0 text-[#7a6c5c]"/>
    <input value={query} onFocus={onActivate} onChange={e=>{onActivate();setQuery(e.target.value)}} onKeyDown={e=>{if(e.key==='Enter')submit()}} placeholder="Search your restaurant's name and city..." className="min-w-[180px] flex-1 bg-transparent py-3 text-base text-[#241b16] outline-none placeholder:text-[#a6957e]"/>
    {loading&&<Loader2 className="h-5 w-5 animate-spin text-[#e51451]"/>}
    <button type="button" onClick={submit} className={`shrink-0 rounded-xl px-5 py-3 text-sm font-bold text-white transition-transform hover:-translate-y-0.5 ${darkButton?'bg-[#241b16]':'bg-[#e51451]'}`}>Get my free score</button>
   </div>
   {active&&suggestions.length>0&&<div className="absolute z-30 mt-2 max-h-72 w-full overflow-y-auto rounded-2xl border border-[#ebe0ce] bg-white p-2 text-[#241b16] shadow-2xl">{suggestions.map(place=><button key={place.placeId} type="button" onClick={()=>choose(place)} className="w-full rounded-xl px-4 py-3 text-left hover:bg-[#fbf6ee]"><b className="block">{place.displayName}</b><span className="text-sm text-[#7a6c5c]">{place.formattedAddress}</span></button>)}</div>}
  </div>
  <p className={`mt-3 text-sm ${darkButton?'text-white/75':'text-[#7a6c5c]'}`}>{note}</p>
  {active&&error&&<p className={`mt-2 text-sm ${darkButton?'text-white':'text-[#b80f40]'}`}>{error}</p>}
 </div>
}

function LandingPage({query,setQuery,suggestions,loading,error,choose,submit}:{query:string;setQuery:(value:string)=>void;suggestions:Place[];loading:boolean;error:string;choose:(place:Place)=>void;submit:()=>void}){
 const [activeSearch,setActiveSearch]=useState<'hero'|'final'>('hero')
 const sampleScores=[
  {title:'Website + Ordering',score:76,label:'Strong',color:'#1e9a56',track:'#e7f7ee'},
  {title:'Reputation & Reviews',score:63,label:'Needs work',color:'#d9861f',track:'#fcf1de'},
  {title:'Getting Customers Back',score:24,label:'Critical',color:'#dc3b3b',track:'#fdecec'},
 ]
 const pillars=[
  {title:'Website + Ordering',finding:'Order buttons buried three clicks deep.',Icon:CalendarDays},
  {title:'Reputation & Reviews',finding:'Fewer than 1 in 20 reviews get a reply.',Icon:Eye},
  {title:'Getting Customers Back',finding:'Fewer than 1 in 5 sites collect an email or phone number.',Icon:Users},
  {title:'Staying Connected',finding:'Inconsistent posting is the top engagement killer.',Icon:Activity},
  {title:'Knowing What Works',finding:"Most can't say which marketing dollar is working.",Icon:BarChart3},
 ]
 return <main className="min-h-screen bg-[#fbf6ee] text-[#241b16]">
  <Header landing/>
  <section className="mx-auto grid max-w-[1080px] gap-11 px-5 pb-16 pt-5 md:grid-cols-[1.05fr_.95fr] md:items-center md:px-6">
   <div>
    <p className="text-xs font-bold uppercase tracking-[.08em] text-[#e51451]">Restaurant Growth Audit</p>
    <h1 className="mt-4 text-4xl font-extrabold leading-[1.08] tracking-[-.035em] sm:text-5xl">See how much revenue you&apos;re <span className="text-[#e51451]">quietly losing</span>, every month.</h1>
    <p className="mt-4 max-w-xl text-lg leading-7 text-[#7a6c5c]">A free, 2-minute check of your website, reviews, and marketing, built from your own data.</p>
    <div className="mt-7"><LandingSearch query={query} setQuery={setQuery} suggestions={suggestions} loading={loading} error={error} choose={choose} submit={submit} active={activeSearch==='hero'} onActivate={()=>setActiveSearch('hero')} note="Turn on your location to find local restaurants."/></div>
    <div className="mt-6 flex flex-wrap gap-2.5">{['Free audit','No login required','Built from public data'].map(label=><span key={label} className="flex items-center gap-1.5 rounded-full border border-[#ebe0ce] bg-white px-3 py-2 text-xs font-semibold text-[#7a6c5c]"><CheckCircle2 className="h-4 w-4 text-[#1e9a56]"/>{label}</span>)}</div>
   </div>
   <div className="relative rounded-[22px] border border-[#ebe0ce] bg-white p-7 shadow-[0_30px_60px_-30px_rgba(36,27,22,.35)]">
    <span className="absolute -top-3 left-6 rounded-full bg-[#241b16] px-3 py-1.5 text-[11px] font-bold tracking-wide text-white">What you&apos;ll see</span>
    <div className="flex items-center gap-5">
     <div className="relative h-[92px] w-[92px] shrink-0"><svg viewBox="0 0 92 92" className="h-full w-full -rotate-90"><circle cx="46" cy="46" r="38" fill="none" stroke="#efe6d5" strokeWidth="10"/><circle cx="46" cy="46" r="38" fill="none" stroke="#d9861f" strokeWidth="10" strokeLinecap="round" strokeDasharray="239" strokeDashoffset="120"/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><strong className="text-2xl font-extrabold leading-none">50</strong><span className="text-[10px] text-[#7a6c5c]">/ 100</span></div></div>
     <div className="text-xs text-[#7a6c5c]">Sample restaurant<b className="block text-base text-[#241b16]">Your Restaurant Here</b></div>
    </div>
    <div className="mt-4 flex flex-wrap gap-1.5"><span className="rounded-full bg-[#e7f7ee] px-2.5 py-1 text-[11px] font-bold text-[#146b3a]">Ordering: Strong</span><span className="rounded-full bg-[#fcf1de] px-2.5 py-1 text-[11px] font-bold text-[#8a5a10]">Reputation: Needs work</span><span className="rounded-full bg-[#fdecec] px-2.5 py-1 text-[11px] font-bold text-[#a32a2a]">Retention: Critical</span></div>
    <div className="mt-4 rounded-[14px] bg-gradient-to-br from-[#b80f40] to-[#e51451] px-4 py-3.5 text-white"><span className="block text-[10px] font-bold uppercase tracking-[.08em] text-[#fbc7d6]">Estimated monthly impact</span><strong className="mt-0.5 block text-2xl font-extrabold">$3,900 / month</strong></div>
    <p className="mt-3.5 text-center text-xs text-[#7a6c5c]">Real example. Yours will be built from your own data.</p>
   </div>
  </section>

  <section className="border-y border-[#ebe0ce] bg-white"><div className="mx-auto grid max-w-[1080px] grid-cols-2 gap-6 px-5 py-6 text-center md:grid-cols-4 md:px-6">{[['700+','Restaurants audited'],['2 min','Average time to results'],['5','Growth areas checked'],['$0','Cost to find out']].map(([value,label])=><div key={label}><strong className="block text-2xl font-extrabold text-[#b80f40]">{value}</strong><span className="text-xs text-[#7a6c5c]">{label}</span></div>)}</div></section>

  <section className="mx-auto max-w-[1080px] px-5 py-20 md:px-6">
   <div className="mx-auto mb-11 max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.08em] text-[#e51451]">Real audit, real example</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.025em]">Exactly what your results will look like</h2></div>
   <div className="grid items-stretch gap-4 md:grid-cols-3">{sampleScores.map(item=><div key={item.title} className="flex h-full flex-col rounded-2xl border-l-[5px] bg-white px-6 py-5 shadow-[0_10px_26px_-18px_rgba(36,27,22,.28)]" style={{borderLeftColor:item.color}}><div className="flex min-h-12 items-start justify-between gap-4"><h3 className="font-bold">{item.title}</h3><strong className="text-2xl font-extrabold" style={{color:item.color}}>{item.score}</strong></div><div className="mt-auto h-2 overflow-hidden rounded-full" style={{background:item.track}}><div className="h-full rounded-full" style={{width:`${item.score}%`,background:item.color}}/></div><span className="mt-2 block text-[11px] font-bold uppercase tracking-wide" style={{color:item.color}}>{item.label}</span></div>)}</div>
  </section>

  <section className="mx-auto max-w-[1080px] px-5 pb-20 md:px-6">
   <div className="mx-auto mb-11 max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.08em] text-[#e51451]">What the audit checks</p><h2 className="mt-3 text-3xl font-extrabold leading-tight tracking-[-.025em]">Five things that decide whether a hungry customer becomes your customer</h2></div>
   <div className="grid items-stretch gap-4 sm:grid-cols-2 lg:grid-cols-5">{pillars.map(({title,finding,Icon})=><div key={title} className="flex h-full flex-col rounded-2xl bg-white p-5 shadow-[0_10px_26px_-18px_rgba(36,27,22,.28)]"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#fdeaf0] text-[#b80f40]"><Icon className="h-5 w-5"/></span><h3 className="mt-4 min-h-12 font-bold">{title}</h3><div className="mt-3 flex-1 rounded-xl bg-[#fbf6ee] p-3 text-sm leading-5"><b className="mb-1 block text-[10px] uppercase tracking-wide text-[#7a6c5c]">What we often find</b>{finding}</div></div>)}</div>
  </section>

  <section className="mx-auto max-w-[1080px] px-5 pb-20 md:px-6"><div className="rounded-[26px] bg-gradient-to-br from-[#e51451] to-[#b80f40] px-6 py-12 text-center text-white md:px-10"><h2 className="mx-auto max-w-xl text-3xl font-extrabold">See your restaurant&apos;s real score, free.</h2><p className="mt-3 text-[#fbdce6]">Takes about 2 minutes.</p><div className="mx-auto mt-7 max-w-xl text-left"><LandingSearch query={query} setQuery={setQuery} suggestions={suggestions} loading={loading} error={error} choose={choose} submit={submit} active={activeSearch==='final'} onActivate={()=>setActiveSearch('final')} darkButton note="Free audit. No login required."/></div></div></section>

  <footer className="flex flex-col items-center justify-center gap-2 px-5 pb-12 text-center text-sm text-[#7a6c5c] sm:flex-row sm:gap-2.5"><a href="https://tossdown.com" target="_blank" rel="noopener noreferrer" className="font-semibold hover:text-[#241b16]">tossdown.com</a><span className="hidden text-[#d8cbb4] sm:inline">|</span><a href="tel:+18552424254" className="font-semibold hover:text-[#241b16]">+1 (855) 242-4254</a><span className="hidden text-[#d8cbb4] sm:inline">|</span><a href="mailto:info@tossdown.com" className="font-semibold hover:text-[#241b16]">info@tossdown.com</a></footer>
 </main>
}

export default function Home(){
 const [query,setQuery]=useState(''),[suggestions,setSuggestions]=useState<Place[]>([]),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(false),[auditing,setAuditing]=useState(false),[audit,setAudit]=useState<any>(null),[error,setError]=useState(''),[auditStage,setAuditStage]=useState(0),[showLead,setShowLead]=useState(false),[unlocked,setUnlocked]=useState(false),[userLocation,setUserLocation]=useState<{lat:number;lng:number}|null>(null)
 useEffect(()=>{if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(position=>setUserLocation({lat:position.coords.latitude,lng:position.coords.longitude}),()=>{}, {enableHighAccuracy:false,maximumAge:600000,timeout:5000})},[])
 useEffect(()=>{const controller=new AbortController();const t=setTimeout(async()=>{if(query.trim().length<3){setSuggestions([]);return}try{const params=new URLSearchParams({input:query.trim()});if(userLocation){params.set('lat',String(userLocation.lat));params.set('lng',String(userLocation.lng))}const r=await fetch(`/api/places/autocomplete?${params}`,{signal:controller.signal}),d=await r.json();setSuggestions(d.suggestions??[]);if(d.error)setError(d.error)}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError('Search is temporarily unavailable. Please try again.')}},350);return()=>{clearTimeout(t);controller.abort()}},[query,userLocation])
 async function choose(p:Place){setLoading(true);setSuggestions([]);try{const r=await fetch(`/api/places/details?placeId=${p.placeId}`),d=await r.json();if(!r.ok){setError(d.error??'Could not load location.');return}setDetail(d);trackAuditEvent('restaurant_selected',{restaurant_category:d.primaryType||'unknown',has_google_website:Boolean(d.googleWebsiteUrl||d.websiteUrl)});try{const q=new URLSearchParams({name:d.name,address:d.address});if(d.websiteUrl)q.set('url',d.websiteUrl);const sr=await fetch(`/api/social/discover?${q}`),sd=await sr.json();const assets:Asset[]=Array.isArray(sd.assets)?sd.assets:[];const social=Object.fromEntries(assets.filter(a=>a.kind==='social'&&a.platform&&a.verification!=='candidate_needs_confirmation').map(a=>[a.platform!,a.url]));const found=sd.websiteUrl||assets.find(a=>a.kind==='website')?.url||'';console.info('[growth-audit][asset-discovery]',{restaurant:d.name,status:sr.status,websiteUrl:found,platforms:Object.keys(sd.socials??{}),diagnostics:sd.diagnostics});setDetail(prev=>prev?{...prev,websiteUrl:prev.googleWebsiteUrl||prev.websiteUrl||found,socials:{...social,...d.socials},brandAssets:assets,discoveryDiagnostics:sd.diagnostics}:prev)}catch(e){console.warn('[growth-audit][asset-discovery] request failed',e)}}finally{setLoading(false)}}
 function submitSearch(){if(suggestions[0]){void choose(suggestions[0]);return}setError(query.trim().length<3?'Enter at least 3 characters to search.':'Select your restaurant from the search results.')}
 async function runAudit(){if(!detail)return;const current=detail;trackAuditEvent('audit_started',{restaurant_category:current.primaryType||'unknown',has_website:Boolean(current.websiteUrl),social_profile_count:Object.keys(current.socials).length});setAuditing(true);setAuditStage(0);setError('');const timer=window.setInterval(()=>setAuditStage(s=>Math.min(s+1,stages.length-1)),1800);try{const r=await fetch('/api/direct-audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(current)}),d=await r.json();if(!r.ok){setError(d.error??'Audit failed.');return}setAudit(d);setShowLead(true);trackAuditEvent('audit_completed',{growth_score:typeof d.result?.score==='number'?d.result.score:0,evidence_coverage:typeof d.result?.coverage==='number'?d.result.coverage:0})}catch{setError('Audit could not connect.')}finally{clearInterval(timer);setAuditing(false)}}
 async function unlock(lead:Lead){if(!detail||!audit)return;const id=`sub_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;trackAuditEvent('generate_lead',{restaurant_category:detail.primaryType||'unknown'});fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,submissionId:id,profile:{placeId:detail.placeId,name:detail.name}})}).catch(()=>{});setUnlocked(true);setShowLead(false);persist(detail,audit,lead,id)}
 async function persist(current:Detail,data:any,lead:Lead,id:string){try{const r=await fetch('/api/audits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({detail:current,audit:data,lead})});if(!r.ok)return;const saved=await r.json();if(!saved.url)return;trackAuditEvent('report_shared',{growth_score:data.result?.score??0});if(saved.id)history.replaceState(null,'',`/r/${saved.id}`);fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,submissionId:id,reportUrl:saved.url,reportSummary:{score:data.result?.score,rating:current.rating,reviews:current.reviewCount}})}).catch(()=>{})}catch{}}
 if(audit&&unlocked)return <Report audit={audit} onReset={()=>{setAudit(null);setDetail(null);setQuery('');setShowLead(false);setUnlocked(false);history.replaceState(null,'','/')}}/>
 if(audit&&showLead&&detail)return <LockedReport audit={audit} restaurant={detail.name} back={()=>{setAudit(null);setShowLead(false)}} submit={unlock}/>
 return <><LandingPage query={query} setQuery={value=>{setQuery(value);setError('')}} suggestions={suggestions} loading={loading} error={error} choose={place=>{void choose(place)}} submit={submitSearch}/>{detail&&<Confirm detail={detail} setDetail={setDetail} next={runAudit} auditing={auditing} stage={auditStage} error={error}/>}</>
}

function Confirm({detail,setDetail,next,auditing,stage,error}:{detail:Detail;setDetail:(d:Detail|null)=>void;next:()=>void;auditing:boolean;stage:number;error:string}){const [err,setErr]=useState('');const discovering=!detail.placeId.startsWith('manual_')&&!detail.discoveryDiagnostics;function proceed(){if(discovering||auditing)return;try{const u=new URL(detail.websiteUrl.trim());if(!/^https?:$/.test(u.protocol))throw new Error()}catch{setErr('Website could not be found. Add a valid website URL to continue.');return}next()}const missing=!detail.googleWebsiteUrl;return <Overlay step={1}>{!auditing&&<button onClick={()=>setDetail(null)} className="mb-6 text-sm text-muted-foreground">← Search again</button>}<div className={`rounded-[2rem] border border-border bg-card p-7 shadow-xl md:p-10 ${auditing?'audit-running-card':''}`}><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{auditing?`Auditing ${detail.name}`:'Verify the right restaurant'}</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">{auditing?'Reading your restaurant growth engine.':detail.name}</h2><p className="mt-2 text-muted-foreground">{auditing?'Live public signals are being gathered and connected into one report.':detail.address}</p>{auditing?<AuditProgress stage={stage}/>:<>{discovering?<div className="mt-7 flex items-center gap-3 rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm"><Loader2 className="h-5 w-5 animate-spin text-primary"/><div><b>Finding website and social profiles…</b><p className="mt-1 text-muted-foreground">Stay here while we enrich the restaurant details for verification.</p></div></div>:<div className="mt-7 rounded-2xl bg-muted p-4 text-sm leading-6"><b>Details ready:</b> verify the website below, then start the free audit. Social profiles are optional.</div>}<div className="mt-7 grid gap-4"><Field label="Website · required" value={detail.websiteUrl} onChange={v=>{setErr('');setDetail({...detail,websiteUrl:v})}} placeholder="https://yourrestaurant.com" hint={missing?'Not linked on the selected Google Business Profile. Please confirm or add it.':''} error={err}/>{['instagram','facebook','tiktok'].map(k=><Field key={k} label={k[0].toUpperCase()+k.slice(1)} value={detail.socials[k]||''} onChange={v=>setDetail({...detail,socials:{...detail.socials,[k]:v}})} placeholder={`https://${k}.com/…`}/>)}</div><button onClick={proceed} disabled={discovering} className="mt-8 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-4 font-semibold text-white disabled:cursor-wait disabled:opacity-55">{discovering?'Finding digital channels…':'Verify details and run free audit'} {discovering?<Loader2 className="h-5 w-5 animate-spin"/>:<ArrowRight className="h-5 w-5"/>}</button>{error&&<p className="mt-3 text-sm text-danger">{error}</p>}</>}</div></Overlay>}
function Overlay({step,children}:{step:0|1|2;children:React.ReactNode}){return <div className="fixed inset-0 z-20 overflow-y-auto bg-background/75 px-5 py-8 backdrop-blur-sm"><Steps active={step}/><div className="mx-auto max-w-2xl">{children}</div></div>}
function AuditProgress({stage}:{stage:number}){return <div className="mt-8"><div className="audit-orbit"><Gauge className="h-10 w-10 text-primary"/></div><div className="mt-8 grid gap-3">{stages.map((x,i)=><div key={x} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm transition-all ${i===stage?'bg-muted text-foreground shadow-sm':'text-muted-foreground'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full border ${i<=stage?'border-primary bg-primary text-white':'border-border'}`}>{i<stage?<Check className="h-4 w-4"/>:i===stage?<Loader2 className="h-4 w-4 animate-spin"/>:i+1}</span>{x}</div>)}</div></div>}
function Field({label,value,onChange,placeholder,hint,error}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;hint?:string;error?:string}){return <label className="grid gap-2 text-sm font-medium">{label}<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={`rounded-xl border bg-background px-4 py-3 font-normal outline-none focus:ring-2 focus:ring-primary/30 ${error?'border-danger':'border-border'}`}/>{hint&&<span className="text-xs font-normal text-muted-foreground">{hint}</span>}{error&&<span className="text-xs font-normal text-danger">{error}</span>}</label>}
function countries(){const all=getCountries();return [...preferred.filter(c=>all.includes(c)),...all.filter(c=>!preferred.includes(c)).sort()]}
function LockedReport({audit,restaurant,back,submit}:{audit:any;restaurant:string;back:()=>void;submit:(x:Lead)=>void}){return <main className="relative h-screen overflow-hidden bg-background"><div className="pointer-events-none select-none opacity-55 blur-[7px]" aria-hidden="true"><Report audit={audit} onReset={()=>{}}/></div><div className="absolute inset-0 bg-gradient-to-b from-background/20 via-background/35 to-background/70"/><LeadForm restaurant={restaurant} back={back} submit={submit}/></main>}
function LeadForm({restaurant,back,submit}:{restaurant:string;back:()=>void;submit:(x:Lead)=>void}){const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[role,setRole]=useState('Owner'),[country,setCountry]=useState<CountryCode>('US'),[err,setErr]=useState('');function send(e:React.FormEvent){e.preventDefault();const national=country==='PK'?phone.trim().replace(/^0/,''):phone.trim();const parsed=parsePhoneNumberFromString(national,country);if(!name.trim())return setErr('Please enter your name.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return setErr('Please enter a valid email.');if(!parsed?.isValid())return setErr('Please enter a valid phone number.');submit({name,email,phone:parsed.number,role})}return <Overlay step={2}><div className="mx-auto max-w-xl"><form onSubmit={send} className="rounded-[2rem] border border-border bg-card p-7 shadow-2xl md:p-9"><button type="button" onClick={back} className="mb-5 text-sm text-muted-foreground">← Start again</button><p className="flex gap-2 text-xs font-semibold uppercase tracking-[.18em] text-primary"><CheckCircle2 className="h-4 w-4"/>Your free audit is ready</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em]">Your free report for {restaurant} is ready.</h2><p className="mt-2 text-sm text-muted-foreground">Add your details to view the complete score, evidence and priorities. No payment required.</p><div className="mt-6 grid gap-4"><Field label="Full name" value={name} onChange={setName} placeholder="Jane Doe"/><Field label="Work email" value={email} onChange={setEmail} placeholder="jane@restaurant.com"/><label className="grid gap-2 text-sm font-medium">Phone<div className="flex gap-2"><select value={country} onChange={e=>{setCountry(e.target.value as CountryCode);setErr('')}} className="rounded-xl border border-border bg-background px-2">{countries().map(c=><option key={c} value={c}>{c} +{getCountryCallingCode(c)}</option>)}</select><input value={phone} onChange={e=>{setPhone(e.target.value);setErr('')}} inputMode="tel" autoComplete="tel-national" placeholder={country==='PK'?'321 4007711':'Phone number'} className="w-full rounded-xl border border-border bg-background px-3 py-3"/></div></label><label className="grid gap-2 text-sm font-medium">Role<select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3">{roles.map(r=><option key={r}>{r}</option>)}</select></label></div>{err&&<p className="mt-3 text-sm text-danger">{err}</p>}<button className="mt-6 w-full rounded-xl bg-primary px-5 py-4 font-semibold text-white">View my free report</button><p className="mt-4 flex justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4"/>100% free. No card or login required.</p></form></div></Overlay>}
